CREATE SCHEMA IF NOT EXISTS BLUESOFT_FINANCAS_PESSOAIS;
USE BLUESOFT_FINANCAS_PESSOAIS;

CREATE TABLE IF NOT EXISTS BLUESOFT_FINANCAS_PESSOAIS.endereco (
	ID_ENDERECO INT NOT NULL AUTO_INCREMENT,
	CEP VARCHAR(8) NULL,
	RUA VARCHAR(150) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	COMPLEMENTO VARCHAR(100) NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	PAIS VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS BLUESOFT_FINANCAS_PESSOAIS.cliente (
	ID_CLIENTE INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NOME_COMPLETO VARCHAR(150) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	DATA_DE_NASCIMENTO DATE NULL,
	PROFISSAO VARCHAR(100) NULL,
	GENERO VARCHAR(1) NULL,
	ENDERECO INT NOT NULL,  
	PRIMARY KEY (ID_CLIENTE),
	FOREIGN KEY (ENDERECO) REFERENCES endereco(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS BLUESOFT_FINANCAS_PESSOAIS.conta_corrente (
	ID_CONTA_CORRENTE INT NOT NULL AUTO_INCREMENT,
	CODIGO_BANCO VARCHAR(5) NOT NULL,
	NUMERO_CONTA VARCHAR(50) NOT NULL,
	AGENCIA VARCHAR(5) NOT NULL,
	APELIDO VARCHAR(50) NOT NULL,
	SALDO DOUBLE NULL,
	CLIENTE INT UNSIGNED NOT NULL,
	PRIMARY KEY (ID_CONTA_CORRENTE),
	FOREIGN KEY (CLIENTE) REFERENCES cliente(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS BLUESOFT_FINANCAS_PESSOAIS.movimentacao_financeira(
  ID_MOVIMENTACAO INT NOT NULL AUTO_INCREMENT,
  VALOR FLOAT(10,2) NOT NULL,
  DATA DATE NOT NULL,
  CATEGORIA VARCHAR(100) NOT NULL,
  CONTA_CORRENTE INT NOT NULL,
  PRIMARY KEY (ID_MOVIMENTACAO),
  FOREIGN KEY (CONTA_CORRENTE) REFERENCES conta_corrente(ID_CONTA_CORRENTE)
);